version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - run:
          command: python -m venv venv
          name: Creating venv
      - run:
          command: ./venv/bin/pip install -r requirements.txt
          name: Install requirements
      - run:
          command: ./venv/bin/pytest main_test.py
          name: Test
      - run:
          command:./venv/bin/flake8 main_test.py
          name: Lint
jobs:
  deploy-lambda:
    executor: python/default
    steps:
      - checkout
      - run:
          command: python -m venv venv
          name: Creating venv
      - run:
          command: ./venv/bin/pip install -r requirements.txt
          name: Install requirements
      - run:
        command: ./venv/bin/zappa update
        name: deploy production

workflows:
  main:
    jobs:
      - build-and-test
      - deploy-lambda:
        requires:
          - build-and-test
        filters:
          branches:
            only:
              -master
          
