version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build-and-test:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run:
          command: python -m venv venv
          name: Creating venv
      - run:
          command: ./venv/bin/pip install -r requirements.txt
          name: Install requirements
      - run:
          command: ./venv/bin/pytest main_test.py
          name: Test
      - run:
          command: ./venv/bin/flake8 main_test.py
          name: Lint


  deploy-lambda:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run:
          command: python -m venv venv
          name: Creating venv
      - run:
          command: ./venv/bin/pip install -r requirements.txt
          name: Install requirements
      - run:
          command: ./venv/bin/zappa update
          name: Deploy production

workflows:
  main:
    jobs:
      - build-and-test
      - deploy-lambda
      #   requires:
      #     - build-and-test
      #   filters:
      #     branches:
      #       only:
      #         -master
          
