version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build-and-test:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run:
          command: python -m venv venv
          name: Creating venv
      - run:
          command: ./venv/bin/pip install -r requirements.txt
          name: Install requirements
      - run:
          command: ./venv/bin/pytest main_test.py
          name: Test
      - run:
          command: ./venv/bin/flake8 main_test.py
          name: Lint


  deploy-lambda:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run:
          command: | 
            mkdir -p ~/.aws &&
            echo "[default]" >> ~/.aws/credentials &&
            echo "aws_access_key_id = $AWS_ACCESS_KEY_ID" >> ~/.aws/credentials &&
            echo "aws_secret_access_key = $AWS_SECRET_ACCESS_KEY" >> ~/.aws/credentials
          name: Create aws profile
      - run:
          command: cat ~/.aws/credentials
          name: Creating venv
      - run:
          command: python -m venv venv
          name: Creating venv
      - run:
          command: ./venv/bin/pip install -r requirements.txt
          name: Install requirements
      - run:
          command: source venv/bin/activate && zappa update
          name: Deploy production
  package-zappa:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run:
          command: | 
            mkdir -p ~/.aws &&
            echo "[default]" >> ~/.aws/credentials &&
            echo "aws_access_key_id = $AWS_ACCESS_KEY_ID" >> ~/.aws/credentials &&
            echo "aws_secret_access_key = $AWS_SECRET_ACCESS_KEY" >> ~/.aws/credentials
          name: Create aws profile
      - run:
          command: cat ~/.aws/credentials
          name: Creating venv
      - run:
          command: python -m venv venv
          name: Creating venv
      - run:
          command: ./venv/bin/pip install -r requirements.txt
          name: Install requirements
      - run:
          command: source venv/bin/activate && zappa package -o lambda_function.zip
          name: Deploy production
      - store_artifacts:
          path: lambda_function.zip
          destination: lambda_function.zip


workflows:
  main:
    jobs:
      - build-and-test
      - approve-deploy
        type: approval
        requires:
          - build-and-test
      - deploy-lambda
        requires:
          - build-and-test
          - approve-deploy
        filters:
          branches:
            only:
              - master
      - package-zappa
        requires:
          - build-and-test

          
